services:
  - type: web
    name: portfolio-backend-v2
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:10000 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8
      - key: PORT
        value: 10000 